spring:
  application:
    name: system-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xuecheng-system
    username: root
    password: 12345678
# 日志文件配置路径
logging:
  config: classpath:log4j2-dev.xml


